Repository tukcomCD2024/JinJiHan, pull requests merged in 2024-03, with the labels that each got.

#13 Feat/#9 backend news entity
  .gitignore
  backend/src/main/java/com/rollthedice/backend/domain/news/entity/Bookmark.java
  backend/src/main/java/com/rollthedice/backend/domain/news/entity/News.java
  backend/src/main/java/com/rollthedice/backend/domain/news/entity/ReadNews.java
  backend/src/main/java/com/rollthedice/backend/domain/notification/entity/Notification.java
  iOS/RollTheDice/.DS_Store
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/Example/exampleNews.imageset/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/Example/exampleNews.imageset/라이즈-싱글-Love-119-티저-이미지-2 3.jpg
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/Example/exampleNews.imageset/라이즈-싱글-Love-119-티저-이미지-2 4.jpg
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/bob.imageset/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/bob.imageset/Ellipse 148.pdf
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/steve.imageset/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/steve.imageset/Ellipse 149.pdf
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/tim.imageset/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/tim.imageset/Ellipse 144.pdf
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/Bookmark.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/BookmarkListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/BookmarkView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/BookmarkViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/Model/ChatModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatCustomView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatTitleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/MyChatCustomView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/ChatError.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/MockAttachment.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/MockMessage.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/MockUser.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Chat/ChatInteractorProtocol.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Chat/MockChatInteractor.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Data Generation/Lorem.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Data Generation/MockChatData.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Extension/Date+Random.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChatExampleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChatExampleViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChatTitleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChattingView.swift
  iOS/RollTheDice/RollTheDice/Source/View/MainTab/MainTabView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/News.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsView.swift
Labels: ✨ feat

#23 Feat/#19 iOS Sign Up View (회원가입 질문 화면 & 내비게이션 적용)
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/appleLoginBtn.imageset/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/appleLoginBtn.imageset/appleLoginBtn.pdf
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/kakaoLoginBtn.imageset/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/kakaoLoginBtn.imageset/kakaoLoginBtn.pdf
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/General/CustomNavigationBar/CustomNavigationBar.swift
  iOS/RollTheDice/RollTheDice/Source/Model/Path/Path.swift
  iOS/RollTheDice/RollTheDice/Source/Model/Path/PathType.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatType/ChatTypeView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatView.swift
  iOS/RollTheDice/RollTheDice/Source/View/MainTab/MainTabView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpFinishView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpQuestionView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpViewModel.swift
Labels: 🐛 fix, 💄 design, ✨ feat

#26 Feat/#25 Backend Crawling (뉴스 정보 크롤링)
  backend/build.gradle
  backend/src/main/java/com/rollthedice/backend/domain/crawling/NewsCrawlingService.java
  backend/src/main/java/com/rollthedice/backend/domain/dto/NewsUrlDto.java
  backend/src/main/java/com/rollthedice/backend/domain/member/entity/Member.java
  backend/src/main/java/com/rollthedice/backend/domain/member/entity/Role.java
  backend/src/main/java/com/rollthedice/backend/domain/member/entity/SocialType.java
  backend/src/main/java/com/rollthedice/backend/domain/member/entity/Status.java
  backend/src/main/java/com/rollthedice/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/rollthedice/backend/domain/news/entity/News.java
  backend/src/main/java/com/rollthedice/backend/domain/news/repository/NewsRepository.java
  backend/src/main/java/com/rollthedice/backend/domain/news/service/NewsCategory.java
  backend/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/BookmarkListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatType/ChatType.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatType/ChatTypeView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatCustomView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatTitleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatView.swift
  iOS/RollTheDice/RollTheDice/Source/View/MainTab/MainTabView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsListViewModel.swift
Labels: ✨ feat

#28 Feat/#27 Backend Rabbitmq (SpringBoot와 RabbitMQ 연결)
  backend/build.gradle
  backend/src/main/java/com/rollthedice/backend/domain/crawling/NewsCrawlingService.java
  backend/src/main/java/com/rollthedice/backend/domain/news/contentqueue/ContentProducer.java
  backend/src/main/java/com/rollthedice/backend/domain/news/contentqueue/SummarizedContentConsumer.java
  backend/src/main/java/com/rollthedice/backend/domain/news/dto/ContentMessageDto.java
  backend/src/main/java/com/rollthedice/backend/domain/news/dto/NewsUrlDto.java
  backend/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  backend/src/main/java/com/rollthedice/backend/global/config/RabbitMQConfig.java
Labels: ✨ feat

#31 Refactor/#30 Backend Core Directory (core directory 추가)
  backend/core/build.gradle
  backend/core/gradle/wrapper/gradle-wrapper.jar
  backend/core/gradle/wrapper/gradle-wrapper.properties
  backend/core/gradlew
  backend/core/gradlew.bat
  backend/core/settings.gradle
  backend/core/src/main/java/com/rollthedice/backend/BackendApplication.java
  backend/core/src/main/java/com/rollthedice/backend/domain/crawling/NewsCrawlingService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/entity/Member.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/entity/Role.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/entity/SocialType.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/entity/Status.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/repository/MemberRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/contentqueue/ContentProducer.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/contentqueue/SummarizedContentConsumer.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/dto/ContentMessageDto.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/dto/NewsUrlDto.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/entity/Bookmark.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/entity/News.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/entity/ReadNews.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/repository/NewsRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsCategory.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/notification/entity/Notification.java
  backend/core/src/main/java/com/rollthedice/backend/global/config/BaseTimeEntity.java
  backend/core/src/main/java/com/rollthedice/backend/global/config/RabbitMQConfig.java
  backend/core/src/main/java/com/rollthedice/backend/global/config/SecurityConfig.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/service/JwtService.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/util/PasswordUtil.java
  backend/core/src/main/java/com/rollthedice/backend/global/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  backend/core/src/main/java/com/rollthedice/backend/global/login/handler/LoginFailureHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/login/handler/LoginSuccessHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/login/service/LoginService.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/CustomOAuth2User.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/OAuthAttributes.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/handler/OAuth2LoginFailureHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/service/CustomOAuth2UserService.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/userInfo/KakaoOAuth2UserInfo.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/userInfo/OAuth2UserInfo.java
  backend/core/src/main/resources/application.yml
  backend/core/src/test/java/com/rollthedice/backend/BackendApplicationTests.java
  backend/src/main/resources/application.properties
Labels: ♻️ refactor

#32 Feat/#29 News Summary (뉴스 내용 요약 기능 구현)
  backend/ai_response_processor/main.py
  backend/ai_response_processor/news/contentqueue/__init__.py
  backend/ai_response_processor/news/contentqueue/rabbitmq_consumer.py
  backend/ai_response_processor/news/contentqueue/rabbitmq_producer.py
  backend/ai_response_processor/news/crud/__init__.py
  backend/ai_response_processor/news/crud/news_summarizer.py
  backend/ai_response_processor/news/schema/__init__.py
  backend/ai_response_processor/news/schema/message_item.py
  backend/ai_response_processor/requirements.txt
Labels: ✨ feat

#33 Feat/#24 iOS font setting (Pretendard)
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Info.plist
  iOS/RollTheDice/RollTheDice/Resources/Font/Font.swift
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Black.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Bold.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-ExtraBold.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-ExtraLight.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Light.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Medium.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Regular.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-SemiBold.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Thin.otf
Labels: 💄 design

#34 Refactor/#14 Backend Member Nickname (회원가입 시 닉네임 입력)
  backend/core/src/main/java/com/rollthedice/backend/domain/member/controller/LoginController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/dto/SignUpDto.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/entity/Member.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/entity/Role.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/query/AuthService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/service/MemberService.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/OAuthAttributes.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/query/QueryService.java
Labels: ♻️ refactor

#39 Feat/#37 iOS GPT chatting
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/General/CustomNavigationBar/CustomNavigationBar.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatGPT/GPTChat.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatGPT/GPTChatListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatGPT/GPTChatView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatGPT/GPTChatViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/Model/ChatModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatCustomView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatTitleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/MyChatCustomView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/ChatError.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/MockAttachment.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/MockMessage.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/MockUser.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Chat/ChatInteractorProtocol.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Chat/MockChatInteractor.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Data Generation/Lorem.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Data Generation/MockChatData.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Extension/Date+Random.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChatExampleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChatExampleViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChatTitleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChattingView.swift
Labels: 💄 design, ✨ feat

#41 Feat/#36 backend news api (요약된 뉴스 조회)
  backend/core/build.gradle
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/controller/BookmarkController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/entity/Bookmark.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/repository/BookmarkRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/service/BookmarkService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/crawling/NewsCrawlingService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/controller/NewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/dto/response/NewsResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/entity/News.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/mapper/NewsMapper.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/repository/NewsRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  backend/core/src/main/java/com/rollthedice/backend/global/config/SecurityConfig.java
Labels: ✨ feat

#43 Feat/#42 backend swagger
  backend/core/build.gradle
  backend/core/src/main/java/com/rollthedice/backend/global/config/SwaggerConfig.java
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Info.plist
  iOS/RollTheDice/RollTheDice/Resources/Font/Font.swift
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Black.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Bold.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-ExtraBold.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-ExtraLight.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Light.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Medium.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Regular.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-SemiBold.otf
  iOS/RollTheDice/RollTheDice/Resources/Font/Pretendard/Pretendard-Thin.otf
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/appleLoginBtn.imageset/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/appleLoginBtn.imageset/appleLoginBtn.pdf
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/kakaoLoginBtn.imageset/Contents.json
  iOS/RollTheDice/RollTheDice/Resources/ImageAssets.xcassets/SignIn/kakaoLoginBtn.imageset/kakaoLoginBtn.pdf
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/General/CustomNavigationBar/CustomNavigationBar.swift
  iOS/RollTheDice/RollTheDice/Source/Model/Path/Path.swift
  iOS/RollTheDice/RollTheDice/Source/Model/Path/PathType.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/BookmarkListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/BookmarkView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatGPT/GPTChat.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatGPT/GPTChatListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatGPT/GPTChatView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatGPT/GPTChatViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/ChatType/ChatTypeView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/Model/ChatModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatCustomView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatTitleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/AIChatView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/AIChat/MyChatCustomView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/ChatError.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/MockAttachment.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/MockMessage.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Data/MockUser.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Chat/ChatInteractorProtocol.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Chat/MockChatInteractor.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Data Generation/Lorem.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Drivers/Data Generation/MockChatData.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/Extension/Date+Random.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChatExampleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChatExampleViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChatTitleView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Chat/View/ChatTestView/View/ChattingView.swift
  iOS/RollTheDice/RollTheDice/Source/View/MainTab/MainTabView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpFinishView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpQuestionView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpViewModel.swift
Labels: ✨ feat

#45 Fix/#44 backend fastapi env
  backend/ai_response_processor/.gitignore
  backend/ai_response_processor/news/contentqueue/rabbitmq_producer.py
  backend/ai_response_processor/requirements.txt
Labels: 🐛 fix

#47 Fix/#46 signup role (회원 Role 변경 및 RefreshToken 설정)
  backend/core/src/main/java/com/rollthedice/backend/domain/member/entity/Member.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/service/MemberService.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: 🐛 fix

#49 Feat/#48 iOS news api 연결
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Source/Domain/API/APIHeaderManager.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Foundation/APIConstants.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Foundation/BaseTargetType.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/RollTheDiceAPI/RollTheDiceAPI.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/RollTheDiceAPI/RollTheDiceAPINews.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Service/NewsService.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticatedView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticationViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/News.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsListViewModel.swift
Labels: ✨ feat

#53 Feat/#52 Backend RefreshToken에 Redis적용
  backend/core/build.gradle
  backend/core/src/main/java/com/rollthedice/backend/domain/member/entity/Member.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/repository/MemberRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/service/MemberService.java
  backend/core/src/main/java/com/rollthedice/backend/global/advice/ExceptionAdvice.java
  backend/core/src/main/java/com/rollthedice/backend/global/config/RedisConfig.java
  backend/core/src/main/java/com/rollthedice/backend/global/config/SecurityConfig.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/exception/NotFoundTokenException.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/refresh/domain/RefreshToken.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/refresh/repository/RefreshTokenRepository.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/refresh/service/RefreshTokenService.java
  backend/core/src/main/java/com/rollthedice/backend/global/jwt/service/JwtService.java
  backend/core/src/main/java/com/rollthedice/backend/global/login/handler/LoginFailureHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/login/handler/LoginSuccessHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/login/service/LoginService.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
Labels: ✨ feat
