Repository tukcomCD2024/JinJiHan, pull requests merged in 2024-06, with the labels that each got.

#138 Feat/#134 ios kakaologin
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Resources/Support/Info.plist
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthAPI.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticatedView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticationViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/MainTab/MainTabView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsView.swift
Labels: 🐛 fix, ✨ feat

#140 Test/#54 뉴스 관련 테스트코드 구현
  backend/core/build.gradle
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/entity/News.java
  backend/core/src/main/java/com/rollthedice/backend/domain/notification/entity/Notification.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/ErrorCode.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/ErrorResponse.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/GlobalExceptionHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/exception/BusinessException.java
  backend/core/src/main/java/com/rollthedice/backend/global/security/jwt/service/JwtService.java
  backend/core/src/test/java/com/rollthedice/backend/domain/auth/AuthTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/NewsFixture.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/controller/NewsControllerTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/repository/NewsRepositoryTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/service/NewsServiceTest.java
  backend/core/src/test/java/com/rollthedice/backend/global/BaseApiTest.java
  backend/core/src/test/java/com/rollthedice/backend/global/BaseControllerTest.java
  backend/core/src/test/java/com/rollthedice/backend/global/LoginTest.java
  backend/core/src/test/java/com/rollthedice/backend/support/RepositoryTest.java
  backend/core/src/test/java/com/rollthedice/backend/support/database/DatabaseCleanup.java
  backend/core/src/test/java/com/rollthedice/backend/support/database/DatabaseTest.java
  backend/core/src/test/resources/application-test.yml
  backend/core/src/test/resources/application.yml
Labels: 🧪 test

#142 Fix/#141 회원 정보 저장 및 닉네임 업데이트 로직 수정
  backend/core/src/main/java/com/rollthedice/backend/domain/member/api/MemberController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/service/MemberService.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/OAuthAttributes.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/controller/AuthController.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/service/AuthService.java
Labels: 🐛 fix, ♻️ refactor

#144 Feat/#136 통계 관련 기능 구현
  backend/core/build.gradle
  backend/core/src/main/java/com/rollthedice/backend/domain/crawling/NewsCrawlingService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/entity/NewsCategory.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/repository/ReadNewsRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/api/StatisticsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/api/StatisticsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/dto/response/CategoryStatisticsResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/dto/response/DateViewStatisticsResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/repository/ReadNewsCustomRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/repository/ReadNewsCustomRepositoryImpl.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/service/StatisticsService.java
  backend/core/src/main/java/com/rollthedice/backend/global/config/QuerydslConfig.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/api/NewsControllerTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/repository/ReadNewsRepositoryTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/service/NewsServiceTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/statistics/StatisticsFixture.java
  backend/core/src/test/java/com/rollthedice/backend/domain/statistics/api/StatisticsControllerTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/statistics/service/StatisticsServiceTest.java
  backend/core/src/test/java/com/rollthedice/backend/support/RepositoryTest.java
Labels: 📦 chore, ♻️ refactor, ✨ feat, 🧪 test

#151 Feat/#150 토큰 바디에 넘기기 & Swagger 설명 추가
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/dto/response/BookmarkResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/dto/request/DebateMessageRequest.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/dto/request/DebateRoomRequest.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/dto/response/DebateMessageResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/dto/response/DebateRoomResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/dto/response/DebateRoomSaveResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/dto/response/DebateSummaryResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/DebateMessageService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/DebateRoomService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/api/StatisticsApi.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/api/AuthApi.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/api/AuthController.java
  backend/core/src/main/java/com/rollthedice/backend/global/security/jwt/dto/TokenResponse.java
  backend/core/src/main/java/com/rollthedice/backend/global/security/jwt/service/JwtService.java
  iOS/RollTheDice/.DS_Store
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Resources/Support/Info.plist
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/API/TokenManager.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthAPI.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticatedView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticationViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/MainTab/MainTabView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/DetailNewsViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsView.swift
Labels: 📝 docs, ✨ feat

#153 Feat/#149 ios bookmarks api
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/API/APIHeaderManager.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/ScoopAPI/ScoopAPI.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/ScoopAPI/ScoopAPIBookmarks.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/ScoopAPI/ScoopAPILogin.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Service/BookmarksService.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Service/LoginService.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/Auth.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthAPI.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticatedView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticationViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/Bookmark.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/BookmarkListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/BookmarkView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/Bookmarks.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkCard/BookmarksListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Bookmark/BookmarkListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/DetailNewsCard/DetailCardNews.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/DetailNewsCard/DetailNews.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/DetailNewsCard/DetailNewsViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsList/NewsList.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsList/NewsListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsList/NewsListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsList/NewsView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/WebView/WebView.swift
Labels: ✨ feat

#168 Refactor/#166 ReadNews와 News 도메인 분리
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/repository/ReadNewsRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/readNews/api/ReadNewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/readNews/api/ReadNewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/readNews/entity/ReadNews.java
  backend/core/src/main/java/com/rollthedice/backend/domain/readNews/service/ReadNewsService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/repository/ReadNewsCustomRepositoryImpl.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/api/NewsControllerTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/service/NewsServiceTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/readNews/ReadNewsFixture.java
  backend/core/src/test/java/com/rollthedice/backend/domain/readNews/api/ReadNewsControllerTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/readNews/repository/ReadNewsRepositoryTest.java
Labels: ♻️ refactor

#171 Dev backend
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/api/BookmarkApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/api/BookmarkController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/entity/Bookmark.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/entity/DebateMessage.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/entity/DebateRoom.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/ClovaSummary.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/api/MemberApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/api/MemberController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/entity/Member.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/entity/News.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/repository/ReadNewsRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/readNews/api/ReadNewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/readNews/api/ReadNewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/readNews/entity/ReadNews.java
  backend/core/src/main/java/com/rollthedice/backend/domain/readNews/service/ReadNewsService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/api/StatisticsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/api/StatisticsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/statistics/repository/ReadNewsCustomRepositoryImpl.java
  backend/core/src/main/java/com/rollthedice/backend/global/common/BaseTimeEntity.java
  backend/core/src/main/java/com/rollthedice/backend/global/common/response/SuccessCode.java
  backend/core/src/main/java/com/rollthedice/backend/global/common/response/SuccessResponse.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/api/AuthApi.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/api/AuthController.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/api/NewsControllerTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/news/service/NewsServiceTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/readNews/ReadNewsFixture.java
  backend/core/src/test/java/com/rollthedice/backend/domain/readNews/api/ReadNewsControllerTest.java
  backend/core/src/test/java/com/rollthedice/backend/domain/readNews/repository/ReadNewsRepositoryTest.java
Labels: ♻️ refactor, ✨ feat
