Repository tukcomCD2024/JinJiHan, pull requests merged in 2024-05, with the labels that each got.

#104 Dev backend
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/api/BookmarkApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/api/BookmarkController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/api/MemberApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/api/MemberController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/dto/MemberUpdateDto.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsController.java
  backend/core/src/test/java/com/rollthedice/backend/domain/auth/AuthTest.java
Labels: ✨ feat

#107 Feat/#106 Exception Handling
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/service/BookmarkService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/exception/DebateRoomNotFoundException.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/DebateMessageService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/exception/MemberNotFoundException.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/service/MemberService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/dto/response/NewsDetailResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/exception/NewsNotFoundException.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/mapper/NewsMapper.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/ErrorCode.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/ErrorResponse.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/GlobalExceptionHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/exception/BusinessException.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/exception/ExternalApiException.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/service/AuthService.java
Labels: ♻️ refactor, ✨ feat

#108 Dev backend
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/service/BookmarkService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/exception/DebateRoomNotFoundException.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/DebateMessageService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/exception/MemberNotFoundException.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/service/MemberService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/dto/response/NewsDetailResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/exception/NewsNotFoundException.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/mapper/NewsMapper.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/ErrorCode.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/ErrorResponse.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/GlobalExceptionHandler.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/exception/BusinessException.java
  backend/core/src/main/java/com/rollthedice/backend/global/error/exception/ExternalApiException.java
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/service/AuthService.java
Labels: ✨ feat

#110 Fix/#109 회원 정보 중복 저장 해결
  backend/core/src/main/java/com/rollthedice/backend/global/oauth2/service/AuthService.java
Labels: 🐛 fix

#111 Feat/#80 Debate 요약 및 저장 기능 구현
  backend/core/build.gradle
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/dto/response/DebateSummaryResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/entity/DebateRoom.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/ClovaSummary.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/DebateMessageService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/DebateRoomService.java
Labels: 🐛 fix, 📦 chore, ♻️ refactor, ✨ feat

#113 Feat/#105 debate complete
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/dto/response/DebateRoomResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/DebateRoomService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/service/MemberService.java
Labels: ♻️ refactor, ✨ feat

#118 Feat/#115 Bookmark Detail
  backend/core/build.gradle
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/api/BookmarkApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/api/BookmarkController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/dto/response/BookmarkResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/repository/BookmarkRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/service/BookmarkService.java
  backend/core/src/main/java/com/rollthedice/backend/global/config/SwaggerConfig.java
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Source/View/Debate/ChatList/ChatListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Debate/ChatList/RecentNewsCardView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Debate/ChatType/ChatTypeView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Debate/Summary/DebateSummaryView.swift
  iOS/RollTheDice/RollTheDice/Source/View/MainTab/MainTabView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Report/Daily/DailyBarChartView.swift
Labels: 🐛 fix, ✨ feat

#124 Feat/#121 상세 뉴스 조회 api 연결
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Resources/Font/Font.swift
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Service/NewsService.swift
  iOS/RollTheDice/RollTheDice/Source/Model/Path/PathType.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/DetailNewsCard/DetailCardNews.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/News.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsList.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsViewModel.swift
Labels: ✨ feat

#131 Feat/#130 ios 상세 뉴스 url 연결을 위한 web view
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/Model/Path/PathType.swift
  iOS/RollTheDice/RollTheDice/Source/View/Debate/ChatList/ChatListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Debate/ChatList/RecentNewsCardView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/DetailNews.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/DetailNewsCard/DetailCardNews.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsList.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/WebView/WebView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpFinishView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpViewModel.swift
Labels: ✨ feat

#133 Feat/#116 최근 조회한 뉴스 관련 기능 구현
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/repository/DebateMessageRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/DebateMessageService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/dto/response/ReadNewsResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/entity/ReadNews.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/mapper/NewsMapper.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/repository/NewsRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/repository/ReadNewsRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/ReadNewsService.java
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Resources/Font/Font.swift
  iOS/RollTheDice/RollTheDice/Resources/Support/Info.plist
  iOS/RollTheDice/RollTheDice/RollTheDiceApp.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/API/APIHeaderManager.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Foundation/APIConstants.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Foundation/BaseTargetType.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/RollTheDiceAPI/RollTheDiceAPI.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/ScoopAPI/ScoopAPI.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/ScoopAPI/ScoopAPINews.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Service/Log/Extension+Log.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Service/Log/Extension+OSLog.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Service/Log/Log.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Service/Log/MoyaLoggingPlugin.swift
  iOS/RollTheDice/RollTheDice/Source/Domain/Service/NewsService.swift
  iOS/RollTheDice/RollTheDice/Source/Model/Path/PathType.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticatedView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Authentication/AuthenticationViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/Debate/ChatList/ChatListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/Debate/ChatList/RecentNewsCardView.swift
  iOS/RollTheDice/RollTheDice/Source/View/MainTab/MainTabView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/DetailNews.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/DetailNewsCard/DetailCardNews.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/DetailNewsViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/News.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsList.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsListView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsListViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsView.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/NewsViewModel.swift
  iOS/RollTheDice/RollTheDice/Source/View/News/NewsCard/WebView/WebView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignIn/SignInView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpFinishView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpQuestionView.swift
  iOS/RollTheDice/RollTheDice/Source/View/SignUp/SignUpViewModel.swift
Labels: 🎨 style, ♻️ refactor, ✨ feat

#135 Dev backend
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/repository/DebateMessageRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/service/DebateMessageService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/dto/response/ReadNewsResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/entity/ReadNews.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/mapper/NewsMapper.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/repository/NewsRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/repository/ReadNewsRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/ReadNewsService.java
Labels: ♻️ refactor, ✨ feat
