Repository tukcomCD2024/JinJiHan, pull requests merged in 2024-04, with the labels that each got.

#57 Refactor/#55 Backend News Crawling Quantity
  backend/core/src/main/java/com/rollthedice/backend/domain/crawling/NewsCrawlingService.java
Labels: ♻️ refactor

#59 Fix/#56 FastAPI와 RabbitMQ 스트림 연결 끊기는 현상 예외처리
  backend/ai_response_processor/news/contentqueue/rabbitmq_consumer.py
  backend/ai_response_processor/news/contentqueue/rabbitmq_producer.py
  backend/ai_response_processor/news/crud/news_summarizer.py
Labels: 🐛 fix

#11 Build/#10 backend cicd
  .github/workflows/gradle.yml
  backend/core/Dockerfile
  backend/core/docker-compose.yml
  backend/core/src/main/resources/application-prod.yml
  backend/core/src/main/resources/application.yml
Labels: 👷 build

#69 Build/#68 Fastapi CI/CD 설정
  .github/workflows/gradle.yml
  backend/ai_response_processor/Dockerfile
  backend/ai_response_processor/requirements.txt
  backend/docker-compose.yml
Labels: 👷 build, 📦 chore

#74 Feat/#71 backend bookmark
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/controller/BookmarkController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/entity/Bookmark.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/repository/BookmarkRepository.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/service/BookmarkService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/service/NewsService.java
Labels: ✨ feat

#76 Feat/#75 MyPage 사용자 정보 전달
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/service/BookmarkService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/controller/MemberController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/dto/response/MemberResponse.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/service/MemberService.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/controller/NewsController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/dto/response/NewsResponse.java
  backend/core/src/main/java/com/rollthedice/backend/global/config/SecurityConfig.java
Labels: ✨ feat

#85 feat: 화면 요약 뷰 배경
  iOS/RollTheDice/RollTheDice.xcodeproj/project.pbxproj
  iOS/RollTheDice/RollTheDice/Source/View/Debate/Summary/DebateSummaryView.swift
Labels: ✨ feat

#99 Refactor/#98 backend member nickname
  backend/core/src/main/java/com/rollthedice/backend/domain/member/dto/MemberUpdateDto.java
  backend/core/src/test/java/com/rollthedice/backend/domain/auth/AuthTest.java
Labels: 🔥 remove, ♻️ refactor, 🧪 test

#103 Feat/#100 Swagger API 설명 추가
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/api/BookmarkApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/bookmark/api/BookmarkController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/debate/api/DebateController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/api/MemberApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/member/api/MemberController.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsApi.java
  backend/core/src/main/java/com/rollthedice/backend/domain/news/api/NewsController.java
  backend/core/src/test/java/com/rollthedice/backend/domain/auth/AuthTest.java
Labels: ✨ feat
